# 68008 executable makefile stub for Hello World template project

# RAM or ROM
CODE_LOC = RAM

# use multitasking lib
USE_MULTITASK = 1

# no optimization
OPTIMIZE = 0

# no core/gcc
# NO_CORELIB = 1

# Extra libraries
LIBS =

include ../../mk/exe.mk
