# 68008 executable makefile stub for Hello World template project

# RAM or ROM
CODE_LOC = RAM

# no kernel
# USE_KERNEL = 0

# no optimization
OPTIMIZE = s

LINK_SCRIPT = link.ld

# don't link with {ram,rom}.o
NO_STARTUP = 1

# no core/gcc
NO_CORELIB = 1

# Libraries
LIBS = -lhd44780

include ../../mk/exe.mk
